apiVersion: v1
kind: Service
metadata:
        name: influxdb-service
spec:
        type: ClusterIP
        selector:
                app: influxdb
        ports:
                - name: http
                  port: 8086

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: influx-pv-claim
        labels:
                app: influxdb
spec:
        accessModes:
                - ReadWriteOnce
        resources:
                requests:
                        storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: influxdb-deployment
        labels:
                app: influxdb
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: influxdb
        template:
                metadata:
                        labels:
                                app: influxdb
                spec:
                        containers:
                                - name: influxdb
                                  imagePullPolicy: Never
                                  image: my_influxdb
                                  livenessProbe:
                                          exec:
                                                  command: ["pgrep", "influxd"]
                                          initialDelaySeconds: 5
                                          periodSeconds: 5
                                  volumeMounts:
                                          - name: influx-persistent-storage
                                            mountPath: /root/.influxdb
                        volumes:
                                - name: influx-persistent-storage
                                  persistentVolumeClaim:
                                          claimName: influx-pv-claim
