apiVersion: apps/v1
kind: Deployment
metadata:
        name: mysql-deployment
        labels:
                app: amazapp
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: amazapp
        template:
                metadata:
                        labels:
                                app: amazapp
                spec:
                        containers:
                                - name: mysql
                                  imagePullPolicy: Never
                                  image: mysql
                                  ports:
                                          - containerPort: 3306
