apiVersion: apps/v1
kind: Deployment
metadata:
        name: wp-deployment
        labels:
                app: wordpress
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: wordpress
        template:
                metadata:
                        labels:
                                app: wordpress
                spec:
                        containers:
                                - name: wordpress
                                  imagePullPolicy: Never
                                  image: my_wp
                                  ports:
                                          - containerPort: 5050
