apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/address-pool: default-ftps
    metallb.universe.tf/allow-shared-ip: "tag"
spec:
  type: LoadBalancer
  loadBalancerIP: 172.17.0.20
  selector:
    app: ftps
  ports:
    - port: 21
      name: ftps
    - port: 21000
      name: ftps-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: my_ftps
        imagePullPolicy: Never
